# i had chatgpt translate some of my sway config but it did it bad

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

after-startup-command = [
    'exec-and-forget $HOME/.config/aerospace/helper.sh startup'

]

exec-on-workspace-change = [
    '/bin/bash', '-c', '$HOME/.config/aerospace/helper.sh setup-workspace'
]

[mode.main.binding]
    cmd-enter = "exec-and-forget open -n /Applications/kitty.app"

    cmd-left = 'focus left'
    cmd-down = 'focus down'
    cmd-up = 'focus up'
    cmd-right = 'focus right'

    cmd-shift-left = 'move left'
    cmd-shift-down = 'move down'
    cmd-shift-up = 'move up'
    cmd-shift-right = 'move right'

    # cmd-b = 'split horizontal'
    # cmd-v = 'split vertical'


    cmd-shift-f = 'fullscreen'
    cmd-shift-space = 'layout floating tiling'

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    cmd-0 = 'workspace 10'

    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-6 = 'move-node-to-workspace 6'
    cmd-shift-7 = 'move-node-to-workspace 7'
    cmd-shift-8 = 'move-node-to-workspace 8'
    cmd-shift-9 = 'move-node-to-workspace 9'
    cmd-shift-0 = 'move-node-to-workspace 10'

    # cmd-r = 'mode resize'

    # cmd-c = '''exec-and-forget open -na "Firefox" --args --new-tab "https://calendar.google.com/calendar/r"'''

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    # return = 'mode main'
    esc = 'mode main'

