#!/bin/sh

loc=$HOME/.cache/nvim/$1.pipe
grep_output=$(ps aux | grep "\-\-listen $loc")

if [[ $1 == "" ]]
then
	echo "no nameless pipe!"
	exit
fi
if [[ -z $grep_output ]]
then
	vim --listen $loc
	disown $!
	echo "started server at $loc"
else
	echo "server already exists at $loc"
	# echo "grep output $grep_output" 
fi
